id: P4A36CC31
initial_creation_type: input
source_metadata:
  title: Padampa Sangye
  language: bo
  description: 'Texts by and about the famous adept Padampa Sangye (pha dam pa sangs
    rgyas), who was born in the 11th century, visited Tibet on a number of occasions,
    and became renowned as the founder of the Pacifying or Zhijé (zhi byed) tradition:'
  volume:
    c84640cc036640049d1abcb234fea734:
      title: The Thirty Aspirations
      parent: Aspiration Prayers
created_at: '2022-03-01T02:19:27.087635'
last_modified_at: '2022-03-01T02:19:27.087638'
statistics:
  total_words: 321
  total_non_words: 37
quality:
  non_words_ratio: 0.12
